### ISSUE TITLE
Umlauts in Filenames

### ISSUE THREAD

**Issue by apeltzer** [l3iggs/docker-owncloud#1]
Hi!
I'm using umlauts like (ä,ö,ü) in some files, which is causing trouble using this image as the respective files can't be found. Can you maybe add other locales to the image to fix this?

After moving all my files ( 10689 items (and 99 hidden), totalling 6.4 GB) to the ~/Owncloud folder on my client (A 64bit Archlinux machine, latest owncloud-client application). I'm trying to sync my stuff, which is always resulting in the following output in the logfile, and incomplete sync (!):

.../..//...: No such file or directory.

If I just go to my local filesystem, these files are definitely existent and there. Apparently, the owncloud client seems to be unable to sync all of them, with 1,569 files reported to be missing. Server seems fine though, and connection is working properly. 

After renaming a lot of them to something more generic without umlauts, the sync works again :)

This is more a suggestion, less an actual bug report, thought however to share this with everyone!

**Comment by l3iggs** [comment]
sure, I can add some additional locales. Can you suggest any specific locales that you think might fix this?

**Comment by apeltzer** [comment]
Maybe this would be the solution to the problem: 

https://forum.owncloud.org/viewtopic.php?f=3&t=2222

**Comment by l3iggs** [comment]
This seems to be a problem with the upstream project: https://github.com/owncloud/core/issues/2377
please help them fix it there.
