### ISSUE TITLE
Completely not working

### ISSUE THREAD

**Issue by birkhofflee** [l3iggs/docker-owncloud#100]
I tried `docker run --name oc -p 80:80 -d l3iggs/owncloud` and opened up http://<ip>/owncloud,  
the browser told me "<ip> refused to connect."

Seems that httpd is not running?

**Comment by birkhofflee** [comment]
No problem with l3iggs/owncloud:daily.

**Comment by greyltc** [comment]
Why would you be visiting `http:///owncloud`?
This issue is invalid.

**Comment by birkhofflee** [comment]
<img width="318" alt="screen shot 2016-07-15 at 2 42 04 am" src="https://cloud.githubusercontent.com/assets/8148095/16851354/c8275062-4a35-11e6-9230-dd5572ca1ac6.png">

**Comment by birkhofflee** [comment]
Sorry, forgot to check the post preview.
