### ISSUE TITLE
While updating to 9.0.4 from 9.0.2.2: [Exception] Unable to move /usr/share/webapps/owncloud/apps to /usr/share/webapps/owncloud/_apps

### ISSUE THREAD

**Issue by raqbit** [l3iggs/docker-owncloud#101]
While updating to 9.0.4 from 9.0.2.2 I get this: [Exception] Unable to move /usr/share/webapps/owncloud/apps to /usr/share/webapps/owncloud/_apps.

I did change the permissions to updating before hand.
Below is a screenshot of the (relevant parts of) the update page.

---

![Error](http://i.imgur.com/7z4l7Tu.png)

**Comment by raqbit** [comment]
Okay, I went to the owncloud install's homepage, clicked "update" on the blue page that popped up, and it said it succeeded. Not sure if I have a broken install now or not. I guess time will tell. Still this bug is present.

**Comment by greyltc** [comment]
Hm. The exception shown there is not super helpful. "Unable to move" but why? It's not clear to me if this is an issue with my container or with docker's upgrade process.
How, exactly, did you change the permissions prior to upgrading?

**Comment by moarf56** [comment]
Hi, I have the same issue !! 
Core is update but no news app. Any ideas plz ?

**Comment by greyltc** [comment]
What are the permissions on your /usr/share/webapps/owncloud/apps folder?

**Comment by greyltc** [comment]
Closing because no response.
