### ISSUE TITLE
Change ports

### ISSUE THREAD

**Issue by Alacard** [l3iggs/docker-owncloud#102]
Im not sure if this is already a thing. but was wondering if you can add a environment variables where we can set a port for OC to run own, the reason im asking is i already have another docker running on port 80 so being able to tell it to use another port would help out.

**Comment by greyltc** [comment]
Hi @Alacard. This is already a thing.
Have a look at the man page for `docker run` by typing `man docker-run` in your terminal for instructions on how to use docker. You'll see that the `-p` option shown there is for controlling port mappings.
