### ISSUE TITLE
Can not connect to server through HTTP in port 80 but can connect through HTTP in port 443

### ISSUE THREAD

**Issue by dfialho** [l3iggs/docker-owncloud#103]
I have executed the command: `docker run --name oc -p 80:80 -p 443:443 -d l3iggs/owncloud` as indicated in the Usage tutorial. 

I am able to connect to the server with https://localhost/owncloud, but when I try to use HTTP using the URL  http://localhost/owncloud I can not connect to the server. This is specially troubling since let's encrypt is not able to access the server in port 80 during the certificate fetching process to verify ownership of the domain.

**Comment by greyltc** [comment]
A few points here:
A) I've disabled serving up the owncloud server through an unencrypted connection by default. Why would you want to do that anyway?
B) let's encrypt does not visit http://localhost/owncloud verify ownership of your domain. It visits http://yourdomain.tld You can see this site (which should appear empty) by pointing your browser to http://localhost
