### ISSUE TITLE
SQL won't load on latest image?

### ISSUE THREAD

**Issue by M1ntBerryCrunch** [l3iggs/docker-owncloud#107]
n00b warning. I'm learning Docker and have been playing around with it. I had this container working and feel like I have the hang of it all. It's not live yet and I got an update notice so I tried and failed, even after using the permission script which seemed to function. I decided to remove the container and the image to start over. 
Now when I have a fresh container, I get this error when I try to use MySQL with user "root":

> Error while trying to create admin user:
> Failed to connect to the database: An exception occured in the driver:
> SQLSTATE[HY000][2002] No such file or directory

Is there a problem with the container and this version of OC? Am I just really tired?
Thanks.

**Comment by M1ntBerryCrunch** [comment]
"daily" build is working for me.

**Comment by M1ntBerryCrunch** [comment]
Daily build has some errors in the log. I can't find a solid image now. Can someone pull "latest" and see if you can set it up with MySQL please? I'm losing my mind :(

**Comment by greyltc** [comment]
I've recently fixed a problem with MySQL in the underlying image. This issue should now be fixed.
