### ISSUE TITLE
Lets Encrypt fails (SSL method 3)

### ISSUE THREAD

**Issue by miniatur** [l3iggs/docker-owncloud#108]
Hey at first awsome project.

I'd run into issues using method 3 with the latest tag. I'd tryed the 9.0.2-2 where it worked fine so i guess my basic setup is fine.

`docker exec -it owncloud.active sh -c 'EMAIL=mail@mail.de DO_SSL_LETS_ENCRYPT_FETCH=true setup-apache-ssl-key'
Fetching ssl certificate files for sub.domain.tld from letsencrypt.org.
This container's Apache server must be reachable from the Internet via http://sub.domain.tld
An unexpected error occurred:
Bug in pythondialog: expected an empty output from u'infobox', but got: u'Error opening terminal: unknown.\n'Please see the logfile 'certbot.log' for more details.`

grets

**Comment by greyltc** [comment]
Hm. Thanks for the report. I'll have a look into this.

**Comment by greyltc** [comment]
This is a bug with letsencrypt: https://github.com/certbot/certbot/issues/1154
I've implemented a workaround in my container here and verified that method 3 works again.
