### ISSUE TITLE
Permissions with docker in windows

### ISSUE THREAD

**Issue by vvallee** [l3iggs/docker-owncloud#109]
Hi, I've configured with your recommendations, including ;

volumes:
    - /f/Downloads/MEDIA/OWN/data:/usr/share/webapps/owncloud/data
    - /f/Downloads/MEDIA/OWN/config:/usr/share/webapps/owncloud/config

`/bin/chown -R 33 /usr/share/webapps/owncloud/data`
and ;
`docker exec -it oc1 sh -c 'set-oc-perms runtime'`
But the web interface still complains about the permissions. Must be something with windows, any ideas?

**Comment by vvallee** [comment]
I have also tried your nextcloud container, with the same issue :(

**Comment by greyltc** [comment]
hm. I don't really test in Windows, but the nature of docker should hopefully mean it doesn't matter. Maybe another windows user can comment here?

I guess vanilla with no volume mount doesn't give any complaints?
What is the actual exact permissions error message?

**Comment by greyltc** [comment]
Closing because no response from anyone.
