### ISSUE TITLE
add startup script, generate configs from templates

### ISSUE THREAD

**Issue by sils** [l3iggs/docker-owncloud#11]
See how we did it: https://github.com/cw1/docker-centos-owncloud/blob/testing/startup.sh

This, in combination with the templates, is pretty cool IMO because it seperates the templates, the configuration and the initial setup of the image. This is also a waypoint towards being able to configure the image with environment variables as a user.

**Comment by sils** [comment]
see #6

**Comment by l3iggs** [comment]
A very minimal startup script is now present.

**Comment by sils** [comment]
I've debugged my script on https://github.com/sils1297/docker-centos-owncloud btw. so you can copy from it if you want.
- We automatically generate an ssl certificate.
- If you start the container with the volumes from an old one an upgrade is automatically done instead of installation.
- We move the installation to a path settable by the user.

**Comment by sils** [comment]
ah most importantly thats all configurable through passing environment variables through the first run i.e. one can really just clone it from docker hub and doesn't need to fiddle with any files. All params are optional.

https://github.com/sils1297/docker-centos-owncloud#environment-variables

**Comment by l3iggs** [comment]
Your templates are interesting. I don't think i really need them for this project (at this point). It seems configurable enough for most use cases. Having the ability to move around the owncloud install folder doesn't seem like something that's too important to me right now. I am  planning on writing up a how to for setting up a reverse proxy server that I think accomplishes a bit of the functionality you've added with your templates. 

> We automatically generate an ssl certificate.
> I've added a facility for this too, although it's off by default. How to turn it on is in the readme.
> 
> If you start the container with the volumes from an old one an upgrade is automatically done instead of installation.
> I really like this. I think I'll try to implement it.
> 
> ah most importantly thats all configurable through passing environment variables
> Yeah, actually I have most of these defined as docker environment variables as well (just haven't documented it very well). Maybe I should add a wiki page about the env variables.

I'm going to close this and open issues to point out the lack of environment variable documentation and the auto-upgrade.
