### ISSUE TITLE
Harden Security method A doesn't work 

### ISSUE THREAD

**Issue by laurentVasseur** [l3iggs/docker-owncloud#110]
Good morning all, 

First, I have to apologize for my english. 
Second, I'm new in docker system and I try to create my owncloud with this docker.
So I tried to use the method A and I created my server.crt and server.key and I used "-v ~/sslCert:/root/sslKeys". But now, I can't go on the website, my server don't accept the connexion. 

Does anyone have an idea ? 
Is there log file where I can have some informations ? 

Thank for your answers

**Comment by greyltc** [comment]
I've updated my readme here with new instructions for option A. Following those should fix things up for you.
