### ISSUE TITLE
Unable to get Lets Encrypt certificate from 9.1.2-1

### ISSUE THREAD

**Issue by igor-bn** [l3iggs/docker-owncloud#112]
Here is the second issue I faced after updating to l3iggs/owncloud:latest (aka 9.1.2-1).
I get following error from certbot:
```
 - The following errors were reported by the server:

   Domain: home-net.example.com
   Type:   unauthorized
   Detail: Invalid response from
   http://home-net.example.com/.well-known/acme-challenge/3g9fwJ6sFIjdx_1h7xn97s0_uY51rS58oP53BVC7iQU:
   "<?xml version="1.0" encoding="UTF-8"?>
   <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
     "http://www.w3.org/TR/xhtml1/D"

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A record(s) for that domain
   contain(s) the right IP address.
```
Please note, I replaced my domain with "home-net.example.com" in this example.
The output makes me think that Apache delivers some standard web page here (404?) instead of actually serving the file. It looks like apache rules got broken.

**Comment by openserverware** [comment]
I get the same error when following the C option with greyltc/nextcloud:latest.

**Comment by jswetzen** [comment]
I have the same error. I tracked it down to the `certbot` command specifying the webroot to be `/srv/http` and `/etc/httpd/conf/extra/httpd-acme.conf` pointing `.well-known/acme-challenge` to `/var/lib/letsencrypt/`. In a running owncloud container named `oc`, this command fixes it:
```
sudo docker exec -it oc sed -i 's/srv\/http/var\/lib\/letsencrypt/' /usr/sbin/setup-apache-ssl-key
```
I couldn't find where that script is added though.

**Comment by jswetzen** [comment]
There, now I have a pull request  for you @greyltc. It's always easier to get a fix served :)

**Comment by openserverware** [comment]
Much appreciated,

Thank you!

**Comment by greyltc** [comment]
PR accepted. Thanks!
