### ISSUE TITLE
Apache 403 Error - Access Forbidden

### ISSUE THREAD

**Issue by shuaiscott** [l3iggs/docker-owncloud#12]
I ran the instructions on the Docker page, exposed port 80, exposed the config and data volumes, and when I start up the container, all I get is a 403 error in Apache when opening it up in the browser.

Running Debian Wheezy latest

**Comment by shuaiscott** [comment]
Nvm, I had some configuration wrong. Works perfectly, thanks!

**Comment by markopolo123** [comment]
I am having the same issue, what config did you have wrong?

**Comment by markopolo123** [comment]
aha, I was browsing to https://localhost, not https://localhost/owncloud. All good now!
