### ISSUE TITLE
Cannot start the docker - no such file or directory

### ISSUE THREAD

**Issue by jshridha** [l3iggs/docker-owncloud#14]
Using the newest build as of yesterday, I cannot start the owncloud docker with the following error:

FATA[0001] Error response from daemon: Cannot start container f06a9cb7574a1e70542c2890a4cf09a8ff97014428248da8814100a6df8e81c1: exec: "cd /usr; /usr/bin/mysqld_safe --datadir='/var/lib/mysql'& apachectl -DFOREGROUND": stat cd /usr; /usr/bin/mysqld_safe --datadir='/var/lib/mysql'& apachectl -DFOREGROUND: no such file or directory

The docker run command I used was:
docker run --name oc -p 8000:80 -p 8443:443 -d l3iggs/owncloud:latest

**Comment by gvagenas** [comment]
Same here using the latest build.

**Comment by l3iggs** [comment]
Looking into this now.

**Comment by l3iggs** [comment]
I'm pretty sure I've just fixed this with af4a864db22d0569b2f2d70c645a171151146e82, sorry about that.

The new image should hit the docker registry in an hour or two. You can check the status of the build here: https://registry.hub.docker.com/u/l3iggs/owncloud/builds_history/126857/

Once it's built, please `docker pull l3iggs/owncloud` and report back here if I've indeed fixed it!

**Comment by jshridha** [comment]
It seems to be working now, but it looks like it doesn't work correctly with my reverse proxy anymore. I'm not sure why. Can you put a tag on your previous build that was working (br8xmq9rxqf979oxvnrrnzj) so that I can pull it?

**Comment by l3iggs** [comment]
Glad it's working now.
I'm going to close this issue and open a new issue to address your reverse proxy: https://github.com/l3iggs/docker-owncloud/issues/15
