### ISSUE TITLE
Why can't I get my reverse proxy working with the v8.0.3 release?

### ISSUE THREAD

**Issue by l3iggs** [l3iggs/docker-owncloud#15]
@jshridha writes:

> ...it doesn't work correctly with my reverse proxy anymore. I'm not sure why. Can you put a tag on your previous build that was working (br8xmq9rxqf979oxvnrrnzj) so that I can pull it?

**Comment by l3iggs** [comment]
@jshridha:
Unfortunately I don't think the Docker Hub/Registry/whatever it's called gives me the ability to tag a previous build. I don't think older builds are even retained anywhere.

"Tags" In docker need to be setup ahead of time and point to a completely different Dockerfile.

I would like to help solve the proxy issue you're seeing though. Can you give any more details on how it's broken/any error messages? Right now, I'm thinking it could be because of the EXPOSE line's I've recently added to the Dockerfile or because of some change upstream from 8.0.2-->8.0.3

**Comment by l3iggs** [comment]
@jshridha, can you please try:
`docker run --name oc -p 80:80 -p 443:443 -d l3iggs/owncloud:testing`
And see if that fixes your proxy?

**Comment by jshridha** [comment]
I still seem to get the same error with that build:

Internal Server Error
The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.

Technical details
Remote Address: 172.17.42.1
Request ID: 59d28b9f3a2834d6ffacaa69a75b25ba

This is what is in my owncloud.log:
: {\"Message\":\"The requested uri(\\/owncloud\\/index.php\\/apps\\/files\\/) cannot be processed by the script '\\/owncloud\\/\\/index.php')\",\"Code\":0,\"Trace\":\"#0 \\/usr\\/share\\/webapps\\/owncloud\\/lib\\/base.php(782): OC_Request::getRawPathInfo()\n#1 \\/usr\\/share\\/webapps\\/owncloud\\/index.php(36): OC::handleRequest()\n#2 {main}\",\"File\":\"\\/usr\\/share\\/webapps\\/owncloud\\/lib\\/private\\/request.php\",\"Line\":297}","level":4,"time":"2015-05-01T11:33:56+00:00"}

**Comment by l3iggs** [comment]
Can you provide a few details on how you set it up so I can try to reproduce it on my end?

**Comment by jshridha** [comment]
Of course!

Docker run command:
docker run --name oc -p 8001:80 -p 8444:443 -d l3iggs/owncloud:testing

Added the following lines to config.php (substituting in my own hostname):
  'overwrite.cli.url' => 'https://www.domain.com/owncloud',
  'overwritehost' => 'www.domain.com',
  'overwriteprotocol' => 'https',
  'overwritewebroot' => '/owncloud',

Apache config file for reverse proxy:
<VirtualHost *:443>
        ServerName domain.com
        ServerAlias domain.com
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www

```
SSLProxyEngine On
    SSLProxyVerify none
    SSLProxyCheckPeerName off
SSLProxyCheckPeerExpire off

SSLEngine on
    SSLProtocol all -SSLv2
    SSLProxyCheckPeerCN off
    SSLCipherSuite ALL:!ADH:!EXPORT:!SSLv2:RC4+RSA:+HIGH:+MEDIUM
    SSLCertificateFile /config/ssl.crt
    SSLCertificateKeyFile /config/ssl.key
    SSLCertificateChainFile /config/ca.pem

     <Location /owncloud>
            ProxyPass http://local.lan:8001/owncloud/
            ProxyPassReverse http://local.lan:8001/owncloud/
    </Location>
```

</VirtualHost>

**Comment by l3iggs** [comment]
I have not been able to reproduce your issue yet but, I was reading here:
https://doc.owncloud.org/server/8.0/admin_manual/configuration_server/reverse_proxy_configuration.html

Maybe your `'overwritewebroot' => '/owncloud',` line is missing a domain name?

**Comment by jshridha** [comment]
I tried changing that to www.domain.com/owncloud, but that doesn't appear to work. I will say that my current settings were working perfectly with your 8.0.2 docker. Maybe something in owncloud's code changed that is preventing the reverse proxy. I'm going to try to rebuild your 8.0.2 docker and see if that solves my problem.

**Comment by jshridha** [comment]
I cloned your git repositories for owncloud, lamp, archlinux, and archlinux-aur and went back in time to the end of march before your most recent commits. I then rebuilt all the docker images. In the owncloud image, I manually installed v8.0.2 using the release from github with the 8.0.2 tag. This still results in the same issue as I was having before. I have no idea what the problem is since it seems I went back to the last known good configuration.

You say you're not able to reproduce my problem with your reverse proxy. Can you send me your reverse proxy settings? Also, I should add, I'm only seeing this error message after I log in to the owncloud server.

**Comment by l3iggs** [comment]
@jshridha

> I tried changing that to www.domain.com/owncloud, but that doesn't appear to work.

www.domain.com is an example, you need to replace it with a host.domain appropriate for your setup.

How do you plan to reach your owncloud server? What address would you hope to type, assuming your reverse proxy was working.

> I cloned your git repositories for owncloud, lamp, archlinux, and archlinux-aur and went back in time...have no idea what the problem is...

I would have expected that to work too. I guess this suggests that the issue isn't with any of the things you rolled back. Has your docker installation been updated? How about your kernel, or anything else relevant on your host machine? Chasing this down sounds really annoying :-/

> You say you're not able to reproduce my problem with your reverse proxy...

And by that, I mean I don't have a working reverse proxy setup, but I've never had one (or even tried to have one) before this, so that doesn't mean too much.

**Comment by jshridha** [comment]
Within my lan, the owncloud server is hosted on a local hostname that resolves to owncloud.lan (192.168.1.100) for example.

The reverse proxy sits at https://www.domain.com and forwards all requests for https://www.domain.com/owncloud to https://owncloud.lan/owncloud

**Comment by l3iggs** [comment]
I don't understand why you're using domain.com
I think it's quite unlikely you own domain.com so using that makes no sense to me.

**Comment by jshridha** [comment]
Sorry, that is just an example. I substitute my own domain into there.

**Comment by l3iggs** [comment]
Ahh.
Have you tried setting it up without using ssl? i.e. changing all the configs so that http://... should work? Maybe it's a ssl issue.

Also, you should look into the apache server log in the container to see if it contains any useful info, it's in /var/log/httpd/error_log

And also obviously the http server error log on your proxy server.

**Comment by l3iggs** [comment]
I was just looking more closely at your apache config file you posted above.
Shouldn't you have https://... in your `ProxyPass` and `ProxyPassReverse` lines under `<Location /owncloud>`?

**Comment by l3iggs** [comment]
Also, the ports you lave listed there are wrong I think. When you run the container, you map its internal https port 443 to 8444 on the host. I would expect your proxy to point to 8444. Instead, you have 8001

**Comment by l3iggs** [comment]
@jshridha, you might try the latest image (ready in an hour or so) it could possibly fix this.

**Comment by jshridha** [comment]
@l3iggs, I've tried doing it both ways - by forwarding to http://owncloud.lan:8001/owncloud and to https://owncloud.lan:8444/owncloud and both yield the same results. I have another docker by pschmitt that is working mostly correctly, so I'm pretty sure its not the reverse proxy settings. Maybe its a php setting. I wonder if the problem is one of the packages installed by pacman. I'm going to translate your docker into ubuntu/debian and see if it helps the problem.

**Comment by l3iggs** [comment]
Have you tried playing with adding `--hostname="owncloud.lan"` to your run command?

**Comment by jshridha** [comment]
This is the contents of my httpd error_log file on a clean install. It's curious that the htaccesstest.txt file does not actually exist. After it fully initializes, these lines stop appearing in the error log.

```
[Tue May 05 13:33:42.992102 2015] [ssl:warn] [pid 11] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.93. Set the 'ServerName' directive globally to suppress this message
[Tue May 05 13:33:43.005673 2015] [ssl:warn] [pid 11] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue May 05 13:33:43.005775 2015] [lbmethod_heartbeat:notice] [pid 11] AH02282: No slotmem from mod_heartmonitor
[Tue May 05 13:33:43.112662 2015] [mpm_prefork:notice] [pid 11] AH00163: Apache/2.4.12 (Unix) OpenSSL/1.0.2a PHP/5.6.8 configured -- resuming normal operations
[Tue May 05 13:33:43.112696 2015] [core:notice] [pid 11] AH00094: Command line: '/usr/bin/httpd -D FOREGROUND'
[Tue May 05 13:36:50.678284 2015] [autoindex:error] [pid 124] [client 192.168.1.50:57745] AH01276: Cannot serve directory /srv/http/: No matching DirectoryIndex (index.html,index.php,index.html) found, and server-generated directory index forbidden by Options directive
[Tue May 05 13:36:53.637849 2015] [authz_core:error] [pid 126] [client 172.17.42.1:45617] AH01630: client denied by server configuration: /usr/share/webapps/owncloud/data/htaccesstest.txt
[Tue May 05 13:36:53.639900 2015] [authz_core:error] [pid 127] [client 172.17.42.1:45619] AH01630: client denied by server configuration: /usr/share/webapps/owncloud/data/htaccesstest.txt
[Tue May 05 13:37:02.935218 2015] [authz_core:error] [pid 160] [client 172.17.42.1:45622] AH01630: client denied by server configuration: /usr/share/webapps/owncloud/data/htaccesstest.txt
[Tue May 05 13:37:02.936860 2015] [authz_core:error] [pid 123] [client 172.17.42.1:45624] AH01630: client denied by server configuration: /usr/share/webapps/owncloud/data/htaccesstest.txt
```

I tried playing with the --hostname flag and that didn't appear to help at all.

**Comment by l3iggs** [comment]
I've got a reverse proxy working. Will post details here when I have a few free minutes.

**Comment by jshridha** [comment]
Awesome. Thanks so much! I've been really banging my head against the wall trying to figure this out.

**Comment by l3iggs** [comment]
I put a page in the wiki describing how I did it: https://github.com/l3iggs/docker-owncloud/wiki/Reverse-proxy-example-(using-Apache)

I'm going to close this since I no loner think my container is what's stopping you from getting your reverse proxy working, but feel free to continue the dialog in here if you need to.

**Comment by jshridha** [comment]
I can't believe this. The issue was the trailing slash at the end of my confguration.

I needed to change:

```
ProxyPass http://local.lan:8001/owncloud/
```

To

```
ProxyPass http://local.lan:8001/owncloud
```

Thanks again so much for helping out and I'm really sorry the issue ended up being so minor and on my side.

**Comment by l3iggs** [comment]
No prob! I'm glad you got it working and happy I could help!
