### ISSUE TITLE
Cannot create or write in datadirectory /usr/share/webapps/owncloud/data

### ISSUE THREAD

**Issue by alterlai** [l3iggs/docker-owncloud#16]
I just followed your instructions on how to install the container. I don't know if this is relevant information but since i already have an Apache server running on the host pc, i changed the port from 80 to 9998.

Command i used to run the container: docker run --name oc -p 9998:80 -p 443:443 -d l3iggs/owncloud

When i want to finish the installation by entering a username and password, it says:
Cannot create or write in datadirectory /usr/share/webapps/owncloud/data

Is this a known issue or does this have something to do with the port?

Thanks.

**Comment by jshridha** [comment]
I've seen this issue too. I had to do a:

docker exec -it oc bash

And then:

chown -R 33:33 /usr/share/webapps/owncloud

The docker should set these permissions automatically at the first run, but it doesn't appear to.

**Comment by alterlai** [comment]
@jshridha Yep that fixed the issue. Thanks a lot!

**Comment by l3iggs** [comment]
This is certainly an issue, I can recreate it.
I'm working on a fix so you don't need the `docker exec -it oc bash` stuff.

**Comment by l3iggs** [comment]
This is fixed now. The new image should be ready to pull in an hour or so.
