### ISSUE TITLE
readme: Add instructions on how to spawn it up persistently

### ISSUE THREAD

**Issue by sils** [l3iggs/docker-owncloud#19]
As this is a server application, people would probably love to have the info on how they can start the container so that it is restarted on every reboot without having to crawl through docker docs.

**Comment by l3iggs** [comment]
Isn't this dependent on the host?

**Comment by sils** [comment]
I think you can just do `--restart='always'` if your docker service is started at startup, that however is indeed host dependent and also usually given.

**Comment by l3iggs** [comment]
I've never actually tried this, but [this page](https://docs.docker.com/articles/host_integration/) makes it seem more complicated than that.

**Comment by sils** [comment]
> As of Docker 1.2, restart policies are the built-in Docker mechanism for restarting containers when they exit. If set, restart policies will be used when the Docker daemon starts up, as typically happens after a system boot. Restart policies will ensure that linked containers are started in the correct order.
> 
> **If restart policies don't suit your needs** (i.e., you have non-Docker processes that depend on Docker containers), you can use a process manager like upstart, systemd or supervisor instead.

how about https://docs.docker.com/reference/commandline/cli/#restart-policies

**Comment by l3iggs** [comment]
systemd starts the docker service on boot on all my machines. I'll test the `--restart='always'` switch to see if that brings the container up at boot.

**Comment by l3iggs** [comment]
Nice!
Added to the documentation: https://github.com/l3iggs/docker-owncloud/wiki/Ensure-your-ownCloud-server-is-always-running
