### ISSUE TITLE
Mariadb: can't log in using root + blank password

### ISSUE THREAD

**Issue by julien-c** [l3iggs/docker-owncloud#2]
(Sorry for duplicating my comment from there: https://registry.hub.docker.com/u/l3iggs/owncloud/)

**Comment by l3iggs** [comment]
Hey, no prob. It's fixed now. Can you verify and close this issue?

**Comment by greysAcademicCode** [comment]
This is fixed now. I fixed it in the upsteram LAMP image

**Comment by l3iggs** [comment]
This is fixed now. I fixed it in the upsteram LAMP image
