### ISSUE TITLE
genSSLKey.sh missing

### ISSUE THREAD

**Issue by ronnicek** [l3iggs/docker-owncloud#25]
Hi,

script genSSLKey.sh is missing in /etc/httpd/conf/ so it always generate (or re-use) localhost ssl keys.

**Comment by l3iggs** [comment]
Hi. Nice llama.
Could you please let me know the exact error message or issue you're seeing?
I just checked, and `/etc/httpd/conf/genSSLKey.sh` does indeed exist in the image.

Maybe you're using an old/outdated image?
You can run `docker pull l3iggs/owncloud` and that will download the latest container.

**Comment by ronnicek** [comment]
Hi,

hehe.. that's really me.. sorry for that, I had image from last week, so I though that it's there also. Updated and problem solved :+1:
