### ISSUE TITLE
Improve SSL security

### ISSUE THREAD

**Issue by jschilperoord** [l3iggs/docker-owncloud#28]
The current docker image is vulnerable to the Poodle attack. Also the RC4 cipher is still supported and should be disabled.

If you need pointers how to improve this you could read this:

(https://raymii.org/s/tutorials/Strong_SSL_Security_On_Apache2.html)

**Comment by l3iggs** [comment]
Thanks very much for pointing these out.

**Comment by jschilperoord** [comment]
You're welcome :-)

2015-05-19 22:17 GMT+02:00 l3iggs notifications@github.com:

**Comment by l3iggs** [comment]
This container uses openssl 1.0.2.a which I don't think is vulnerable to POODLE. Correct me if I'm wrong on that though. I'll do some more testing to prove this to you/myself.

**Comment by jschilperoord** [comment]
If you run owncloud yourself with your image(using SSL). You could check ssllabs to let them check your SSL configuration. This was a scan I executed on our server: https://www.ssllabs.com/ssltest/analyze.html?d=files.tangelo.nl&hideResults=on

This scan mentioned that my server is vulnerable to the poodle attack

**Comment by l3iggs** [comment]
I've fixed everything up. Please pull a new image and test it and let me know if you're satisfied with the SSL security so I can close this.

**Comment by jschilperoord** [comment]
Ssllabs is showing me a nice A now instead of a C. Thanks for your prompt response. You can close this issue.
