### ISSUE TITLE
ERROR 403

### ISSUE THREAD

**Issue by metal3d** [l3iggs/docker-owncloud#29]
Hi

I tried to launch your image. There is the `docker ps` output:

```
67f6fa434ca5        l3iggs/owncloud:latest                       "/root/startServers.   2 minutes ago       Up 2 minutes        443/tcp, 80/tcp          oc
```

Getting container ip, I go to
http://172.170.243

Then get a 403 error.

Same if I map ports to the host (-p option) for both 80 and 443. 

Going on the ssl port, the browser tells that cert is not verified, I accept the certificate, and then... 403 error.

Any idea ?

EDIT: I tried too with 

```
docker rm oc
docker run --name oc -p 10080:80 -p 10443:443  l3iggs/owncloud
```

Returning:

```

curl -L http://127.0.0.1:10080
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<title>Access forbidden!</title>
<link rev="made" href="mailto:you@example.com" />
<style type="text/css"><!--/*--><![CDATA[/*><!--*/ 
    body { color: #000000; background-color: #FFFFFF; }
    a:link { color: #0000CC; }
    p, address {margin-left: 3em;}
    span {font-size: smaller;}
/*]]>*/--></style>
</head>

<body>
<h1>Access forbidden!</h1>
<p>




    You don't have permission to access the requested directory.
    There is either no index document or the directory is read-protected.



</p>
<p>
If you think this is a server error, please contact
the <a href="mailto:you@example.com">webmaster</a>.

</p>

<h2>Error 403</h2>
<address>
  <a href="/">127.0.0.1</a><br />
  <span>Apache/2.4.12 (Unix) OpenSSL/1.0.2a PHP/5.6.9</span>
</address>
</body>
</html>
```

**Comment by l3iggs** [comment]
Hi. Have you tried browsing to `http://${WHATEVER_IP_ADDRESS}/owncloud` ?

Did you make any modifications to the container launch command (from step 2 in the readme)?

**Comment by metal3d** [comment]
You can now label this issue "shame on this reporter" :)

That works, a big sorry !

**Comment by l3iggs** [comment]
No prob!
If you'd like the sever to be served up at `/`, see the `TARGET_SUBDIR` variable in the wiki here: https://github.com/l3iggs/docker-owncloud/wiki/Environment-Variables
