### ISSUE TITLE
Squash docker image

### ISSUE THREAD

**Issue by fuerst** [l3iggs/docker-owncloud#30]
Running docker 1.6.0 on an OpenVZ containers leaves only the _vfs_ file system option. That means the layers of the docker image can not share common files. Every layer will use its whole size on disk. Using the latest owncloud image adds up to nearly 80 GB. 

May be you can use https://github.com/jwilder/docker-squash to reduce the amount of layers? As far as I understand it leaves the base layer untouched and squashes the layers on top of it to one resulting layer. This will also reduce the amount of data to be loaded through the net when installing your image.

**Comment by l3iggs** [comment]
Yeah, I agree that image size is an issue for sure. I think it's better addressed by the Docker team though.
Here is a discussion about solving it in what I think is the "right way":
https://github.com/docker/docker/issues/332
With the PR awaiting a design review here:
https://github.com/docker/docker/pull/12198

So I'm hopeful this will be solved properly upstream soon and I can just add the MARK and SQUASH directives to the Dockerfile and everything will be great.

Do you think you can wait for the Docker folks to fix it upstream?

**Comment by fuerst** [comment]
That's fine for me - I just switched from the OpenVZ container to a KVM based virtual machine so I can use AUFS instead of VFS now. Using AUFS same files between layers are reused.

**Comment by l3iggs** [comment]
Ok. I'll close the issue for now then.
