### ISSUE TITLE
Access owncloud using bridged interface

### ISSUE THREAD

**Issue by ITFactoryAUT** [l3iggs/docker-owncloud#33]
Hello,
i´m using bridged interfaces for docker and with an fix ip and an brided interface I´m not able to connect over port 80 or 443.
I tried to view the iptables, but it tells me that I´m no root and stuff like that.
Whats wrong here?
greetings
Nico

**Comment by l3iggs** [comment]
Hi Nico,
I assume you're trying to manipulate iptables inside my l3iggs/owncloud container. I don't think you should have to do that. If you want to map the server to ports other than 80 or 443 you should adjust the docker command line to suit your needs. [Reading up on how to do this with Docker here might help you](https://docs.docker.com/articles/basics/#bind-docker-to-another-hostport-or-a-unix-socket).

If for some reason, you really do need to manipulate iptables in the docker image you should know that the default user in the container is not `root` it's a user I made called `docker`. `docker` has passwordless sudo permissions, so to switch to the root user you can run `sudo su`.

I'm not entirely sure exactly how Docker manages the network interfaces inside the container. I  guess there's a pretty good chance that whatever you know about iptables in general, does not apply inside a Docker container.

**Comment by l3iggs** [comment]
I assume this is solved since Nico/ITFactoryAUT has not responded.
