### ISSUE TITLE
webdav has strange 1MB limit, though file uploads are allowed up to several GB

### ISSUE THREAD

**Issue by HostToday** [l3iggs/docker-owncloud#34]
webdav has strange 1MB limit, though file uploads are allowed up to several GB

**Comment by l3iggs** [comment]
Hmm. Thanks for pointing this out. I'll have a look.
To be clear:
You can upload "large" files, but you can't download anything larger than 1MB?

**Comment by HostToday** [comment]
sorry for the unclear starement: by 'allowed' i mean the settings in the dockerfile/htaccess file. when trying to upload files larger than 1MB through webdav, webdav returns 'entity too large'.

**Comment by HostToday** [comment]
this happens with the stock dockerfile and the 30G initial settings.

**Comment by l3iggs** [comment]
@HostToday I've made a few changes to DAV and tested it by uploading and downloading a 500MB file with no issues.

I think I've fixed this with these changes: 015df19cd6ce21e5bddb76b4d4771346de3479fa

**Comment by HostToday** [comment]
Perfect, thank you! We'll test it and report back.
