### ISSUE TITLE
version 8.1 has removed the force https checkbox

### ISSUE THREAD

**Issue by l3iggs** [l3iggs/docker-owncloud#37]
This means (for now) there's no easy way to ensure all traffic is encrypted no matter what.

I need to come up with some other easily configurable way for the user to force https if they wish.

Probably I'll have to use an environment variable passed via the docker command line which modifies the apache config file.

**Comment by tapir** [comment]
:+1:  I was looking for a way to do this.

**Comment by greyltc** [comment]
I'm thinking there's no reason to ever run ownCloud without https.
In fact, I'm planning on completely disabling the http server so that ownCloud can only be accessed via https (making this issue moot).

**Comment by tapir** [comment]
for testing purposes it's good have this option.

**Comment by greyltc** [comment]
Yeah, I guess if you're messing with setting up your SSL cert files and something is not working, it's nice to be able to make sure the site can be reached via the non-ssl route, but does that single use case really justify leaving the insecure http portal running by default for every single install?

**Comment by greyltc** [comment]
With my commit c3452cbb25ed1395c13488eddddeb5101b60e751, visiting the server via http now results in an error message instructing the user to use https instead.

If you'd really like to allow http traffic to your ownCloud (like for testing), you can put `-e ALLOW_INSECURE=true` into the `docker run` command you use to launch the container.
