### ISSUE TITLE
Expose Volumes

### ISSUE THREAD

**Issue by sils** [l3iggs/docker-owncloud#4]
Hi,

would be nice to be able to use volumes with that image.

Here's how we did this:
https://github.com/cw1/docker-centos-owncloud/blob/testing/Dockerfile#L21

Then in the readme one could just create a volume container and then to update the owncloud just fetch the new owncloud container and use it with the same volumes. That is easier and avoids the permission problems while being platform independent.

**Comment by l3iggs** [comment]
715f5676466db6080aa30c99bfcc474f97edd0c8 addresses this
