### ISSUE TITLE
Get changes upstream

### ISSUE THREAD

**Issue by sils** [l3iggs/docker-owncloud#41]
Would be nice to have some of the features in the official docker image https://github.com/docker-library/owncloud . @l3iggs would you be willing to join effort with me and them to make the official one the best one? I already opened a bug at owncloud docs to change installation instructions to use docker and compose: https://github.com/owncloud/documentation/issues/1516

**Comment by l3iggs** [comment]
Yeah, I noticed an "official" image has appeared, it's kind of reduced my motivation to maintain this to be honest...

**Comment by sils** [comment]
Well, so pushing the good stuff of this upstream would be awesome, right? I
find the official image to be quite bare ATM.

2015-08-15 13:41 GMT+02:00 l3iggs notifications@github.com:

**Comment by l3iggs** [comment]
I haven't tried the official image.
If it's worse than this one in some way, it seems that whoever created it/or administers it should look through this one and copy whatever pieces they'd like. I don't personally plan on making/testing/troubleshooting PRs to the official image though.

**Comment by tapir** [comment]
Official one gave me a lot of headaches. It even stopped working completely after enabling encryption. It's not up to the quality of this one yet. So please don't be discouraged :+1:
