### ISSUE TITLE
add news app (RSS Reader)

### ISSUE THREAD

**Issue by baracoder** [l3iggs/docker-owncloud#42]
Please add the news app too
https://aur.archlinux.org/packages/owncloud-app-news/

**Comment by tapir** [comment]
I've installed this myself and it complains that it needs cron or a custom update module.
How can we install cron? Can you add cron to the container?

**Comment by baracoder** [comment]
you should be able to trigger it from the host

```
docker exec CONTAINER sudo -u www-data php -f /var/www/owncloud/cron.php
```

**Comment by tapir** [comment]
That's webcron isn't it? News app doesn't work with Ajax or webcron. It needs cronie. And AFAIK it's not installed on this container.

**Comment by baracoder** [comment]
that is the script which is called by cron for background jobs, see
https://doc.owncloud.org/server/8.2/admin_manual/configuration_server/background_jobs_configuration.html#cron

**Comment by tapir** [comment]
@baracoder I don't understand what you're recommending. How is running cron.php once helps with my problem? cron.php should be run regularly. That's why I need cronie installed.

**Comment by baracoder** [comment]
@tapir you can trigger the file from outside the container so you don't need any daemon inside the container. On the host use in your crontab

```
*/15  *  *  *  * docker exec CONTAINER_NAME sudo -u www-data php -f /var/www/owncloud/cron.php
```

**Comment by tapir** [comment]
@baracoder thanks but that's against the spirit of containers. at least the way I use them. No outside dependencies is my rule.

So instead I've created my own container with everything I need. nginx, php5-fpm, cron, memcache etc...

**Comment by l3iggs** [comment]
Hmm, I don't have fetching form the AUR setup in these containers. I wonder if the Arch maintainers can be convinced to move `owncloud-app-news` to Community...
