### ISSUE TITLE
Automatic setting of username + password

### ISSUE THREAD

**Issue by zopyx** [l3iggs/docker-owncloud#43]
Is there a way to set a username + password automatically as part of running the Docker image?
Usecase is that we need a Docker installation with a pre-defined username/password for integration purposes. We don't want to emulate the setting of the initial account data using screen scrapping or so.
Is this possible?

**Comment by l3iggs** [comment]
Hm. I think it should be. I'm not exactly sure where username and password are stored. It would either be in the database (in whatever type of database you format you choose during setup) or in config.php

Have a look at owncloud's documentation for config.php: https://doc.owncloud.org/server/8.2/admin_manual/configuration_server/config_sample_php_parameters.html
Maybe you can pre-set some variable(s) there to get what you need there. If not, you may need to include a previously created database in your image with he user and password already in there.

**Comment by l3iggs** [comment]
@zopyx any progress with this?

**Comment by greyltc** [comment]
Interest in this feature seems to waned. I don't think I'll spend any effort to try to implement this. I'm happy to accept a PR for it or repoen it if I see some more interest.
