### ISSUE TITLE
Commandline 'occ' is broken

### ISSUE THREAD

**Issue by disconn3ct** [l3iggs/docker-owncloud#44]
I'm actually not sure what is going on, but the PHP CLI doesn't load all the modules:

```
[http@8e83466be335 ~]$ cd /usr/share/webapps/owncloud/
[http@8e83466be335 owncloud]$ php occ
An unhandled exception has been thrown:
OC\HintException: [0]: Missing memcache class \OC\Memcache\XCache for local cache (Is the matching PHP module installed and enabled ?)
```

Removing the cache entry from the owncloud conf makes it worse:

```
[http@8e83466be335 owncloud]$ php occ
The posix extensions are required - see http://php.net/manual/en/book.posix.php
```

`php -m` shows all the necessary modules are loaded and nothing looks odd about `php -i`.

(This is all after adding `/etc/webapps/owncloud/config` to open_basedir.)

**Comment by disconn3ct** [comment]
FYI the reason I'm messing with occ is I'm trying to convert an earlier sqlite install (same repo) over to postgres.

**Comment by l3iggs** [comment]
Fixed by https://github.com/l3iggs/docker-owncloud/pull/47
