### ISSUE TITLE
Storing data duplicating

### ISSUE THREAD

**Issue by ktanriverdi** [l3iggs/docker-owncloud#45]
Hi

When i try to store data on nfs mount,disk size both growing on localhost and nfs mount,How can i handle with this situtaion?

Thanks.

**Comment by l3iggs** [comment]
Sorry, there's not enough info here to even attempt to try to solve this.

**Comment by l3iggs** [comment]
I'm closing this since the issue opener has not provided any more info. Happy to re-open if anyone wants to work with me to solve this thing.
