### ISSUE TITLE
Owncloud 8.2.0 modified time

### ISSUE THREAD

**Issue by ktanriverdi** [l3iggs/docker-owncloud#46]
Hi ,

With new image 8.2.0 uploaded file modified time shows a year later.How can we change this?

**Comment by l3iggs** [comment]
That's odd. Has anyone else seen this?

**Comment by l3iggs** [comment]
@ktanriverdi I've just tried to repeat this and the time stamps are working fine for me. I'll assume this is some issue with your host and not this image.
