### ISSUE TITLE
add tags

### ISSUE THREAD

**Issue by l3iggs** [l3iggs/docker-owncloud#48]
The docker image should have tags that correspond to major owncloud releases.

**Comment by mitar** [comment]
Please add tags. It is really easy with new Docker Hub which allows automatic creation of Docker image tags based on git tags.

**Comment by l3iggs** [comment]
@mitar It's not exactly as simple as throwing in a tag to this github repo. I think that would be very prone to improper tagging since currently _nothing_ in this repo typically changes from one ownCloud release to the next.

I've just had an idea of how to change the way I install ownCloud in this image that might let me make tags that will actually be reliable. I'll give it a shot!

**Comment by l3iggs** [comment]
This is done.
The docker image's tags will correspond to the versions of the owncloud package in the Arch Linux: https://www.archlinux.org/packages/community/any/owncloud/

The `8.2.1-1` tag exists now. I'll tag new releases as they appear.
