### ISSUE TITLE
PHP Module GD not installed

### ISSUE THREAD

**Issue by brookesey** [l3iggs/docker-owncloud#49]
I'm trying to use this repo as a base for a project I'm working on. When I do a manual docker build I get the following:
![image](https://cloud.githubusercontent.com/assets/1423092/11442431/2922b552-950d-11e5-9b1c-065353247773.png)
Do you know how to fix the "PHP module GD not installed" error?

Also, I've successfully used the version on docker hub (https://hub.docker.com/r/l3iggs/owncloud/), but the automated build doesn't seem to be up to date.

Thanks.

**Comment by l3iggs** [comment]
I don't know how the docker hub build could be out of sync with respect to what's in this repo. The docker hub builds are done automatically whenever I push changes.

I will try to recreate this. Can you show me the exact steps you take to do your manual build?

**Comment by brookesey** [comment]
Thanks for updating the build on docker. 

I now get the "PHP module GD not installed" error directly when I pull the image form docker hub.

**Comment by johanneslotz** [comment]
lt looks like the php-gd package is not installed per default  (for me also when installing from docker-hub). Apparently, an additional pacman -Syu is needed to install the most recent php/apache.

so, my shortfix is:

```
docker exec  -ti owncloud bash
pacman -Syu php-gd
apachectl restart
```

**Comment by l3iggs** [comment]
I'm 99.9% sure php-gd is not missing from the image.

php-gd is a dependency for owncloud (see https://www.archlinux.org/packages/community/any/owncloud/) meaning it really is impossible to install owncloud using pacman without php-gd already being installed.

Furthermore, I install php-gd in my docker-lamp image which is the base for docker-owncloud and I've gone back and looked at the build log for that image and it looks like the php-gd install went fine: https://hub.docker.com/r/l3iggs/lamp/builds/b7hwm7ku2pduarskn7k4rmq/

@johanneslotz, you're seeing this issue with the docker-owncloud image you download directly from the docker hub? Could you try your shortfix omitting the pacman line there?

**Comment by l3iggs** [comment]
I'll trigger a complete rebuild from the base image up and we'll see if that somehow fixes things. Stay tuned.

**Comment by johanneslotz** [comment]
I just re-installed the images. 
Sorry, you are right, php-gd is installed, I tried the image that is pulled by `docker pull`.
So for me, a `pacman -Syu` does the trick, installing upgrades of php, apache and some php-modules.

**Comment by l3iggs** [comment]
Ok, then hopefully the rebuild that is going on now will do the trick. It should take ~1.5 hours for the re-builds to ripple up and finish with docker-owncloud.

**Comment by l3iggs** [comment]
Fixed?

**Comment by johanneslotz** [comment]
works like a charm. thanks a lot!

**Comment by brookesey** [comment]
Thanks a lot. Works for me too.
