### ISSUE TITLE
SSL Cert / Bad request!

### ISSUE THREAD

**Issue by LVLAaron** [l3iggs/docker-owncloud#52]
I have resolved issue #51 by not redirecting the /https volume. 

I am able to successfully access the HTTP site after starting the image. 

When I access the HTTPS site, I get 

```
Bad request!

Your browser (or proxy) sent a request that this server could not understand.

If you think this is a server error, please contact the webmaster.
Error 400
www.example.com
Apache/2.4.17 (Unix) OpenSSL/1.0.2e PHP/5.6.16
```

Also, in the readme, the file referenced to generate a new certificate `/etc/httpd/conf/genSSLKey.sh` is set to place the generated files in `/etc/httpd/conf/` - Should those not be moved to `/https` somehow?

**Comment by l3iggs** [comment]
Thanks for the heads up.
I've recently re-worked most of the ssl generatoin code and associated documentation. Hopefully everything's in line now.
