### ISSUE TITLE
Include letsencrypt.org instead of self signed cert?

### ISSUE THREAD

**Issue by jkaberg** [l3iggs/docker-owncloud#53]
https://letsencrypt.org/

Would make things easier and more secure :-)

**Comment by l3iggs** [comment]
Agreed! I'll see what I can do!

**Comment by elangelo** [comment]
@l3iggs any news on this? I'm kind of delaying a new deploy in the hope i can include this immediately...

**Comment by l3iggs** [comment]
Yeah.
I've done a bit of work on getting this going and I think it's almost ready. I ran into some bugs in the letsencrypt packages I was using so that slowed me down a bit. I think they've been fixed now so I'll have another look at getting this working now.

**Comment by greyltc** [comment]
**NOTE: Be careful with this; Let's Encrypt has a rate limit of 5 certificates / 7 days / domain so starting your container like this too often will use up your registrations, then it'll stop working (I just found out the hard way ;-)).**

Ok! I think I've got it working now.

Please test it (and report back here) by doing the following:

``` bash
docker pull l3iggs/owncloud:dev
docker run -e EMAIL="you@youremail.address" -e DO_SSL_LETS_ENCRYPT_FETCH=true --hostname=your.dom.ain --name oc -p 80:80 -p 443:443 -d l3iggs/owncloud:dev
```

From my experience it takes about 20 seconds to get a certificate. I've set the apache server to restart as soon as the cert files come in so waiting 30 seconds or so after starting the image like this should be enough. Now visit https://your.dom.ain/owncloud and you should see a nice green lock in your browser! 

For this to work, your firewall/network setup must be such that your server is accessible from the Internet by visiting http://your.dom.ain i.e. you need a public IP, your domain's DNS servers & registration must be correct and your firewall must allow access via port 80 (at least for the first 30 sec) while the certificate is fetched. Don't ask me why port 80 needs to be open to the internet. This seems to be some strange design decision by the letsencrypt folks or I haven't figured out how to prevent this requirement.

When you verify that this works for you, I'll update the :latest tag with this work so you don't need to use the :dev tag any more.

**Comment by greyltc** [comment]
Bump.
@jkaberg, @elangelo, I'd love to be able to close this.

**Comment by elangelo** [comment]
root@master:~# docker run -e EMAIL="myemailaddress" -e
DO_SSL_LETS_ENCRYPT_FETCH=true --hostname=myhostname --name oc -p 80:80 -p
443:443 -d l3iggs/owncloud:dev -v
/data/owncloud/data:/usr/share/webapps/owncloud/data -v
/data/owncloud/conf:/usr/share/webapps/owncloud/config -v
/data/owncloud/cert:/https
5a16e81a34f11c126f39f07fd4f93b4ca9ecf5669943af2f021814f72eae265f
docker: Error response from daemon: Container command not found or does not
exist..

On Sun, Feb 14, 2016 at 12:51 PM, Grey Christoforo <notifications@github.com

**Comment by greyltc** [comment]
HI @elangelo,
You've used an invalid syntax in your command there. Use the command in my instructions for your testing.

[Here is the documentation](https://docs.docker.com/engine/reference/commandline/run/) on the proper syntax for `docker run`.

By the way, what are you trying to accomplish with your attempt to attach a volume to a folder `/https` in the container? Please point me to whatever you read that lead you to do this, it needs to be cleaned up.

**Comment by elangelo** [comment]
grmbl. I really _HATE_ docker's syntax. why can't i put the volumes at the end... sigh
I don't remember where i got the https thing from. It worked (? did it really? ) on my old machine but indeed doesn't seem to work on the new one, so  I just dropped it. It used to contain my own custom signed certificate.
The letsincrypt thing works perfect. But indeed the hard limit of 5 is easily reached :( 
Luckily i was only trying this with a test domain.

**Comment by elangelo** [comment]
Btw it doesn't play well with -e TARGET_DIR=/ (at least that is what i assume is not working now)

**Comment by greyltc** [comment]
Hm. I can't remember how I did TARGET_DIR atm. Would you mind opening an issue to track that? I'll have a look when I get the chance.

Actually, I don't think the let's encrypt cert stuff is quite perfect yet (it at least gives a green lock so that's pretty good), currently my grade is capped at B in [this test](https://www.ssllabs.com/ssltest/) because I think I haven't properly told apache where to find cert chain file.

Also, letsencrypt issues certs that are good for 90 days. I _think_ I've set it up in a way that will renew your certs without any user intervention. Only time will tell if that works though. If you keep your server up for 90 days, I'd be interested in hearing about any breakage you might see!
