### ISSUE TITLE
Access Forbidden when mapping a host directory to the data path

### ISSUE THREAD

**Issue by minorsecond** [l3iggs/docker-owncloud#55]
Hello,

I tried mapping the ownCloud data directory to /owncloud via "docker run --name oc -p 80:80 -p 443:443 -d -v /owncloud/data:/usr/share/webapps/owncloud l3iggs/owncloud"

When I browse to localhost/owncloud, I receive "Error 403: Access Forbidden." I've tried giving http:http ownership of /owncloud, to no effect. Works perfectly when the default settings are used. 

Any idea on where to go from here?

**Comment by minorsecond** [comment]
Went through thte steps in fixPerms.sh manually, which didn't seem to affect anything.

**Comment by l3iggs** [comment]
Hi @minorsecond, please have a look at the instructions for how to do this [on the wiki here](https://github.com/l3iggs/docker-owncloud/wiki/Using-volumes-with-your-ownCloud-container#storing-your-data-folder-outside-of-the-container) and let me know if that solves things for you. It looks to me like you're mapping to the wrong folder in the container.

**Comment by l3iggs** [comment]
I'm closing this because @minorsecond does not respond.
