### ISSUE TITLE
Use environment variables for configuration

### ISSUE THREAD

**Issue by sils** [l3iggs/docker-owncloud#6]
We experimented a bit with environment variables and I think it would be quite cool to be able to configure a few things with it. This is our experiments: https://github.com/cw1/docker-centos-owncloud/tree/testing

I'm giving you all these bugs/hints because we started to create an own OC image and don't have the time to maintain it so at least someone could profit from our ideas.

**Comment by l3iggs** [comment]
Thanks very much for lending your knowledge! These are great issues/hints! I'll try to address them all.

**Comment by sils** [comment]
You may even take the code from us almost as it is. (I can ask the main author in case you need licensing information.) So far our code also suffers from #8 for me. Would be nice if we can make our image obsolete and join forces for one even greater thing.

**Comment by l3iggs** [comment]
You can check out the environment variables I'm using in the wiki here: https://github.com/l3iggs/docker-owncloud/wiki/Environment-Variables
