### ISSUE TITLE
Calendar sync not possible due to php7 incompatibilities

### ISSUE THREAD

**Issue by codetalker78** [l3iggs/docker-owncloud#60]
Owncloud 8.2 has some issues in combination with php7 that lead to multiple malfunctions. One of them is that CALDAV sync is not possible (webdav also has problems).
Here is the issue in the owncloud bug tracker: https://github.com/owncloud/core/issues/21461

I can confirm that this malfunction is present in the latest docker-owncloud image. Please either revert back to php5 or implement the workaround mentioned in the linked issue.

**Comment by greyltc** [comment]
Hi @codetalker78, I've had a look at the issue you pointed to there and noticed that the last comment says it's fixed by php 7.0.3. Could you please try my most recent :dev tag (which has that version of php7) and report back if things are still broken for you?

Let me know if you need guidance on how to use the :dev tag.

**Comment by codetalker78** [comment]
I did a `docker pull l3iggs/owncloud:dev` which downloaded many new filestystem layers, and then a `docker stop oc`, `docker run --name oc-dev -v [...] -p 80:80 -p 443:443 --link=postgres -d l3iggs/owncloud:dev`
The container shutdown immediately. When adding `--restart="always"`, `docker -ps` continuously showed the container wit status "restarting". `docker logs oc-dev` shows only two lines about mysql starting.
On short: I can't test the calendar sync, because I can't get the container running. Any advice?

**Comment by codetalker78** [comment]
I pulled `:DEV` again tonight and started the owncloud setup from scratch. Now calendar sync via caldav is working as expected!

Thank you for your help with this issue and thank you for the fantastic owncloud image :-)

**Comment by greyltc** [comment]
Ah, great!
I did [this](https://github.com/l3iggs/docker-owncloud/commit/d9bbcb54761e9714febe085090a8928208366846) to fix the :dev branch a few hours ago after I saw you were having problems. I'll probably merge all my recent :dev branch changes into master in the next few hours so you shouldn't need the :dev tag anymore after that.
