### ISSUE TITLE
letsencrypt certificate won't be updated automatically

### ISSUE THREAD

**Issue by elangelo** [l3iggs/docker-owncloud#63]
I could be wrong but i tried reading most of the Dockerfiles that are used by the owncloud container and i don't see anything that can point to the renewal of the certificate.
By default certificates of LetsEncrypt only last 90 days. 
AFAIK you are supposed to run a job with cron to update the certificates every now and then:
the command
letsencrypt renew 
should renew all installed certificates on the machine.

after the call to that command you should also restart apache (apachectl graceful)

https://letsencrypt.org/howitworks/

**Comment by greyltc** [comment]
https://github.com/greyltc/docker-LAMP/blob/master/setupApacheSSLKey.sh#L36
`--renew-by-default` should take care of it.

I'm already restarting apache after the certs come in.

**Comment by elangelo** [comment]
So this command get's run everytime we startup the machine? How about running the command every 90 days? (cause then the certificate will be expired)
As far as i can see you still need to run the letsencrypt command to renew the certificate. You can't expect them to push the certificate to your computer, you have to pull it... hence cron to schedule the fetching 
(this is my understanding of reading the manual of letsencrypt)
