### ISSUE TITLE
mod_rewrite needs to be enabled to use DAV autodiscovery

### ISSUE THREAD

**Issue by jheretic** [l3iggs/docker-owncloud#65]
Hi,

I set up an owncloud instance using this Docker container (works great, thanks!). But I was having some trouble with getting DAVdroid to connect to it. DAVdroid uses well-known URLs to discover CalDAV and CardDAV services on hosts, but these URLs were not available. It turns out that they are created by mod_rewrite directives in /usr/share/webapps/owncloud/.htaccess, but the mod_rewrite module was not enabled. Enabling mod_rewrite in /etc/httpd/conf/httpd.conf would allow webDAV clients to do discovery correctly. I'll be submitting a pull request that enables this support, for your review.

Thanks!

**Comment by greyltc** [comment]
Thanks for this. I've included this fix in my upstream container here: https://github.com/greyltc/docker-LAMP/commit/20bc689032f0d9b0b9d33316944b2dfb54f61b4d 
Give the builds a few minutes to flow down and you can `docker pull l3iggs/owncloud:latest` and make sure everything is working for you (please report back so I can close this).

**Comment by jheretic** [comment]
Thanks @greyltc! I'm a little new to docker; will that command pull down updated intermediate and base images too? Because I don't think anything was updated.

**Comment by greyltc** [comment]
My bad, I had a broken link between docker images (parent build finish should trigger child build). All fixed now! You can see the container's build status here: https://hub.docker.com/r/l3iggs/owncloud/builds/

**Comment by jheretic** [comment]
Ah okay, cool. That's what I thought, but when it didn't work I figured I was doing something wrong. I'll keep an eye on the build status, once it's done I'll try it and let you know. Thanks again!

**Comment by jheretic** [comment]
I think that did it! I seem to be able to load the .well-known URLs now. Thanks!
