### ISSUE TITLE
Unable to add ssl cert

### ISSUE THREAD

**Issue by piercie11** [l3iggs/docker-owncloud#67]
Hello,

I am having issue adding my personal ssl cert to this container. I am currently running your instance in production and having issue adding my own ssl cert. I tired using docker commit command to make a copy of that instance and re-run it while attaching my own ssl keys. The problems is that it keep pull up the server self assigned ssl keys instead. Do you have any suggests on how I can force it take the self assigned keys with out complete wiping it out. I currently have a custom temples and Ldap set up for this.

**Comment by greyltc** [comment]
Have you read the README.md lately on how to do this? Please show me the docker command you're using to start the container. I suspect you're putting your keys in the wrong place in the image.

**Comment by piercie11** [comment]
Hey Greyltc

Below is the command I ran.

docker run --name oc1 -it -p 80:80 -p 25:25 -p 443:443 -e TARGET_SUBDIR=/ --restart='always' -v /mnt/nfs/owncloud-data:/usr/share/webapps/owncloud/data -v /home/ufadmin/sslCert:/root/sslKeys -d l3iggs/owncloud

**Comment by greyltc** [comment]
What do you have in `/home/ufadmin/sslCert`?

**Comment by greyltc** [comment]
And why do have `-it` in there?

**Comment by piercie11** [comment]
Hey greyltc,

I have the company sslCert in there. Also I had the add -it in there so I can login into the container to add temple files to it.
company_domain.ca-bundle  wildcard.company_domain.key
STAR_company_domain.crt

**Comment by greyltc** [comment]
The files should be named exactly `server.crt` and `server.key`, try renaming your files.

**Comment by piercie11** [comment]
Thanks, I will rename them that. And will let know if that fix the issue.

**Comment by greyltc** [comment]
Cool, please do.

**Comment by greyltc** [comment]
Also, when you test this, please let me know if you notice that page rendering is slow.

**Comment by piercie11** [comment]
Still no luck, it still pulls up the self assigned cert. Also made sure I change the permission as well when I changed the names.
For page rendering slow, that an issue I been having with Chrome  when I try to login. I first though it was due to ldap. But I notice that it only happen when I tried to login with google chrome.

**Comment by piercie11** [comment]
I am going to try to create a brand new instance separate then what I am currently using as production to see if that helps.

**Comment by piercie11** [comment]
Hmm so I wasn't able to get it start httpd when I created a new instance. I received the follow error.

[root@files /]# cat /var/log/httpd/error_log
[Fri Mar 04 18:54:07.568936 2016] [ssl:emerg] [pid 17] AH02565: Certificate and private key www.example.com:443:0 from /root/sslKeys/server.crt and /root/sslKeys/server.key do not match
AH00016: Configuration Failed
[Fri Mar 04 18:57:53.171799 2016] [ssl:emerg] [pid 184] AH02565: Certificate and private key www.example.com:443:0 from /root/sslKeys/server.crt and /root/sslKeys/server.key do not match
AH00016: Configuration Failed
[Fri Mar 04 18:57:58.667578 2016] [ssl:emerg] [pid 191] AH02565: Certificate and private key www.example.com:443:0 from /root/sslKeys/server.crt and /root/sslKeys/server.key do not match
AH00016: Configuration Failed
[Fri Mar 04 18:58:02.852328 2016] [ssl:emerg] [pid 198] AH02565: Certificate and private key www.example.com:443:0 from /root/sslKeys/server.crt and /root/sslKeys/server.key do not match
AH00016: Configuration Failed
[Fri Mar 04 18:58:08.355229 2016] [ssl:emerg] [pid 207] AH02565: Certificate and private key www.example.com:443:0 from /root/sslKeys/server.crt and /root/sslKeys/server.key do not match
AH00016: Configuration Failed

**Comment by greyltc** [comment]
That's strange. It looks like your crt and your key don't match. Are you sure your files are good?

**Comment by piercie11** [comment]
Hey greyltc,

I still working on getting new cert to see if that will fix the issue. I will update you once I received and tested it. As far as the rendering issue it seem to be tied with ldap as I have no issue logging in with a local account.

**Comment by greyltc** [comment]
Your error log shows that this is most certainly an issue with your cert files. I've re-just tested adding cert files to the image an it seems to be working fine. I'm going to close the issue now. Feel free to comment on it if there's some new development here.
