### ISSUE TITLE
there is no documentation on how to use letsencrypt in this container

### ISSUE THREAD

**Issue by xogium** [l3iggs/docker-owncloud#68]
Hi,
first of all, I would like to thank you for that really well done job with the container. :)
However, I'm not sure if it is something I'm doing wrong, but I'm not able to use letsencrypt to generate a certificate. I tried, inside the container with a bash shell:

letsencrypt certonly

An unexpected error occured: PythonDialogBug. Please check the logs in /var/log/letsencrypt.

And:

letsencrypt --apache

The apache plugin is not working. There may be some problem with your configuration.

Am I the only one to have those issues ? I did stop apache before doing this, with:

apachectl graceful-stop

I attached my letsencrypt debug log, in case someone could find something useful there.

[letsencrypt.txt](https://github.com/l3iggs/docker-owncloud/files/159761/letsencrypt.txt)
Thanks in advance

**Comment by greyltc** [comment]
`letsencrypt --apache` is invalid (unsupported) for the distribution in this container (Arch).

Admittedly, I haven't had the chance to write up any documentation for using the letsencrypt functionality I've recently built in.

I'll work on putting some instructions in the README.md

**Comment by xogium** [comment]
Hello,
thanks a lot ! :)
I would be glade to help you to test it, if you want some help. Should I close the issue or let it open till there's documentation available ?

**Comment by xogium** [comment]
Hi again,
thanks for your work on providing instructions for letsencrypt :)

But I'm still stuck with an issue.. Maybe I do something wrong though.. When I use the command you provided as an example and replace the EMAIL and HOSTNAME parameter's values, it fails because it's trying to reach my domain but uses the container id instead of my domain name.

Fetching ssl certificate files for 7f0f1eab0021 from letsencrypt.org.
This container's Apache server must be reachable from the Internet via http://7f0f1eab0021
Requested domain 7f0f1eab0021 is not a FQDN
Failed to fetch ssl cert from let's encrypt.

Any idea ?
Thanks

**Comment by greyltc** [comment]
I've updated the README instructions for specifying hostname. Give those a shot.

**Comment by xogium** [comment]
Hello,
Thank you :) . So I stopped the container and used docker rm oc, but my data and config are kept outside so I didn't lose a thing.. When I do docker run again, I'm no longer able to go on my owncloud.. 500 internal server error. accessing localhost works just fine, but localhost/owncloud is no longer working properly.

Do you know what can cause this ?
Thanks

**Comment by greyltc** [comment]
I've heard someone else mention 500 errors before. If you can figure out exactly how to make them appear, please post here: https://github.com/l3iggs/docker-owncloud/issues/69 and I can start to try to solve it.

**Comment by greyltc** [comment]
Where is your database? Is that also outside the image?

**Comment by xogium** [comment]
Hum, I assumed that it was either in the data dictory or the config one.. I'm using two separate dir for config and data on my external hard drive, so it looks like this:
/run/media/xogium/external\ hard\ drive/owncloud-data:/usr/share/webapps/owncloud/data
and:
/run/media/xogium/external\ hard\ drive/occonfig:/usr/share/webapps/owncloud/config

I'm not sure if the database is stored though, but I assumed it was saved in one of those directories.

As for reproducing the 500 error, just start a container (don't know if data stored outside is a requirement), complete the installation process, and start uploading some files. Then, stop the container with docker stop oc, and remove it with docker rm oc. Now, use docker run again. Bam, 500 internal server error.

**Comment by xogium** [comment]
Oh, my bad, I didn,t see the link for the issue 69.. I checked my emails.. and the link didn't show up.. I'm blind, so it may happen sometime :)
sorry again

**Comment by greyltc** [comment]
The very first time you set up your ownCloud server (when you were prompted for your admin name and password) you had the chance to change your database settings. If you did nothing, it defaults to sqlite which I think stores the DB in your data folder in owncloud.db. If you chose MySQL the DB is stored somewhere else and you probably destroyed it when you did `docker rm oc`

**Comment by xogium** [comment]
Woops.. I think that's it.. Any way to recover from that or should I delete everything and start from a fresh owncloud again ? Or maybe just deleting the config.php file may fixe it ?

**Comment by greyltc** [comment]
I'm not 100% sure exactly what goes into the database, but I think it's at least info on the users you've created. I honestly don't know exactly what the best way is to recover from a lost database. You could try to start without config.php.
Worst case: you'll have to start new and re-copy in all the data files you had stored so that ownCloud knows about them again.

**Comment by xogium** [comment]
Hi,
I deleted the config.php file and now it works again.

Do you know where the db is stored ? Also, using docker cp to copy the content of /etc/letsencrypt/live/domain doesn't work.. It only produces an empty directory. Is it working like the usual cp command so you have to use -r ? I didn't see it in docker cp --help.

I'm not too sure about using the (A) option either.. I don't really understand what you mean, and does this means I can't reboot my computer without needing to regenerate a certificate ?
Thanks

**Comment by greyltc** [comment]
here is the documentation for docker cp: https://docs.docker.com/engine/reference/commandline/cp/

It's a relatively new command so maybe you need to update your Docker.

Also, I've changed the README on how to run docker cp to copy out your keys since they're links and the option for docker cp to follow links requires an even newer version of docker. The new copy from location does not contain links so that should be solved.

**Comment by greyltc** [comment]
I'm closing this issue because the documentation on how to use letsencrypt is now "complete" in the README.

**Comment by ghost** [comment]
> I've updated the README instructions for specifying hostname. Give those a shot.

where can i find this ?
