### ISSUE TITLE
Init MySQL 

### ISSUE THREAD

**Issue by ninja-** [l3iggs/docker-owncloud#70]
So, it's really painful to bootstrap docker-owncloud with external MySQL volume mount.
My idea is to add mysql_install at start of container and chmod/chown which would solve this. Currently I had to manually init MySQL out of the container...

**Comment by greyltc** [comment]
Could you run the MySQL server externally and just tell ownCloud (in the container) how to reach your MySQL server?

**Comment by ninja-** [comment]
That didn't change anything afaik. Same behaviour when using linked db

**Comment by greyltc** [comment]
I can't say I really understand what this issue is actually about.

> So, it's really painful to bootstrap docker-owncloud with external MySQL volume mount.  

seems pretty vague to me.

If you've got an idea for solving some pain point you've identified, feel free to submit a PR to fix it and I'll have a look at it and accept it if I like it.

**Comment by holms** [comment]
@ninja- each containers MUST run only ONE process :} Yes you need to use official mariadb image, and pass environment variables for creating new db/user/password/root password. And you need to link db containers to owncloud container. This should be done with docker-compose. That's the proper production way of doing things with docker.

**Comment by greyltc** [comment]
Yep. The proper production way is to point OC to an external MySQL server (possibly also running in another docker container). For convenience/testing purposes, I've included a MariaDB server right in this container.
Here's how to use it:
https://github.com/greyltc/docker-owncloud/wiki/Setup-ownCloud-to-use-MySQL-instead-of-the-default-sqlite-database
