### ISSUE TITLE
OC 9.0 brings errors in log

### ISSUE THREAD

**Issue by greyltc** [l3iggs/docker-owncloud#71]
I just upgraded the image to use ownCloud version 9.0 (from 8.2.2) and it seems to have brought with it a few errors in the log:
`no app in context`
and
`PHP","message":"Undefined index`

**Comment by piercie11** [comment]
Hey @greyltc ,
After the latest pull request I am no longer seeing that issue on my container.

**Comment by greyltc** [comment]
Cool, I'll close this then.
