### ISSUE TITLE
OC 9.0 external storage not working and file upload limits not applied

### ISSUE THREAD

**Issue by mac-linux-free** [l3iggs/docker-owncloud#73]

**Comment by mac-linux-free** [comment]
..and I couldn´t downgrade

**Comment by ninja-** [comment]
Since when is there 9.0 in this image

**Comment by mac-linux-free** [comment]
I did an pacman -Suy in the container.

**Comment by greyltc** [comment]
@ninja-, 9.0 has been in the `:latest` container for 21 hours. It came out 41 hours ago.

@mac-linux-free, Are these bugs with this container or are they with owncloud? how are you attempting to limit file uploads? how are you attempting to use external storage? and what are the errors you get? I tag each version on release, so you can use 8.2.2 if you want by using `l3iggs/owncloud:8.2.2-2`

You might benefit by reading this:
https://owncloud.org/blog/time-to-upgrade-to-owncloud-9-0/

**Comment by greyltc** [comment]
@mac-linux-free, the issue raiser is silent and I've just tested uploading a 4.5GB file with no issues, so the increased upload size limit seems to be working.
I've also just tested external storage (of type SFTP) and that's also working.
In light of these things, I'm closing this now. I'm happy to re-open it if I can get some help from someone who will help me recreate/understand this.
