### ISSUE TITLE
Huge number of layers

### ISSUE THREAD

**Issue by setiseta** [l3iggs/docker-owncloud#75]
Hi,

is there a reason why you are using such a huge number of layers?
If not you should combine all RUN commands to as less as possible.
This should also reduce the image size.

Kind Regards

**Comment by greyltc** [comment]
Hi @setiseta,
No, there's not. Your issue is a duplicate of https://github.com/l3iggs/docker-owncloud/issues/72

**Comment by setiseta** [comment]
Oh sorry i missed this, should i do a pull request or are you changing this?

**Comment by greyltc** [comment]
I'll fix it up. Thanks though.
