### ISSUE TITLE
Cron not working

### ISSUE THREAD

**Issue by nrgeen** [l3iggs/docker-owncloud#78]
It seems that the cron is not run. 
When I run it manually, the command works.

I need the cron for News App. (Same in already solved Issue #42 )

**Comment by greyltc** [comment]
Sorry for breaking this. It should be fixed up now. Let me know please.

**Comment by nrgeen** [comment]
testing... 

thanks!!

**Comment by nrgeen** [comment]
Looks good.
Thank you very much!
