### ISSUE TITLE
Can't access owncloud

### ISSUE THREAD

**Issue by raqbit** [l3iggs/docker-owncloud#79]
`docker logs oc`: 
`
160317 13:15:47 mysqld_safe Logging to '/var/lib/mysql/d8fbd7411ce7.err'.

160317 13:15:47 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
`

command used to start oc:
`
docker run --name oc -v /media/(RAID)/owncloud:/usr/local/webapps/owncloud -v ~/sslCert:/root/sslKeys -p 80:80 -p 443:443 -d l3iggs/owncloud
`

**Comment by greyltc** [comment]
It looks like you've docker volume mapped over the entire owncloud install directory. That's almost certainly a bad idea. Did you mean to do that? Maybe you meant to map to /usr/local/webapps/owncloud/data?

Have you browsed the (github) wiki pages here? https://github.com/l3iggs/docker-owncloud/wiki

**Comment by raqbit** [comment]
New command, same problem:

`docker run -v /media/(RAID)/owncloud/config:/usr/share/webapps/owncloud/config -v /media/(RAID)/owncloud/data:/usr/share/webapps/owncloud/data -v /root/sslCert/:/root/sslKeys --name oc --restart='always' -p 80:80 -p 443:443 -d l3iggs/owncloud
`

**Comment by raqbit** [comment]
When using the mobile owncloud app it does find the SSL cert.  But then in says that an error has occurred.

**Comment by raqbit** [comment]
Alright, It now opens a webpage, (without doing anything), but everything seems broken: http://i.imgur.com/hWFhaA5.png

EDIT: This seems to be Https://Localhost/.

Https://localhost/owncloud DOES bring me to owncloud now!

**Comment by greyltc** [comment]
Great. So we can mark this solved then?

**Comment by raqbit** [comment]
I guess so. But why is there a webpage at https://IP/? And can I remove it?

**Comment by piercie11** [comment]
Hey @JustRamon 
You can do this by rebuilding your instance using this flag "TARGET_SUBDIR=/". This will load Owncloud on the root folder of the web server ex. https://1.1.1.1. You can find more information on this by checking out the Environment Variables section on the [wiki](https://github.com/l3iggs/docker-owncloud/wiki/Environment-Variables).

**Comment by raqbit** [comment]
I know you can do it that way, but I asked why there was a webpage at that url when I didn't set it there.
