### ISSUE TITLE
can't start container

### ISSUE THREAD

**Issue by sils** [l3iggs/docker-owncloud#8]
seems it exits on start immediately.

```
[lasse@schuirlsrv ~]$ docker run --name ocd -p 80:80 -p 443:443 -d l3iggs/owncloud
7dfeecf25d590d411e6d3fb8d3491fe8752f0c9b11c3560e90233ca36d3e554c
[lasse@schuirlsrv ~]$ docker ps -a
CONTAINER ID        IMAGE                    COMMAND                CREATED             STATUS                      PORTS               NAMES
7dfeecf25d59        l3iggs/owncloud:latest   "/bin/sh -c 'cd '/us   10 seconds ago      Exited (1) 8 seconds ago                        ocd  
```

**Comment by sils** [comment]
```
[lasse@schuirlsrv ~]$ docker run l3iggs/owncloud
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.8. Set the 'ServerName' directive globally to suppress this message
```

**Comment by l3iggs** [comment]
Looking into this right now.

**Comment by l3iggs** [comment]
This issue is particularly alarming, but I can not recreate it.

I've just tried rebuilding the Dockerfile locally and pulling the one from the registry and both seem to work fine this is on my Arch Linux box. I've also just tried the image in the owncloud registry on a Debian Sid box and that worked fine there too.

I expect to see the warning you brought up:
`httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.8. Set the 'ServerName' directive globally to suppress this message`
I've made no attempt to set that in the apache config (this may be solved by the -h docker parameter, I'm not sure). However, this is only a warning and I haven't noticed any issues that arise from it.

Can you try again, making sure you have the latest image? what OS and docker version are you seeing this on?

**Comment by sils** [comment]
I was using Fedora 22 alpha as host system with the latest docker available for it. (Can't look up the version number right now because I don't have access to this system here in the train :).) However it should be independent on the host system. I'd rather suspect it has something to do with the local network configuration but there it ends for me right now.

I used the latest image pulled an hour earlier or so from docker hub.

**Comment by l3iggs** [comment]
From what you just wrote in #6, this must somehow be specific to your setup. I know many people are not having this image terminate immediately when they run it.

I'd definitely like to get to the bottom of this.

Next time you see this issue please run

```
docker run -i --name oc -p 80:80 -p 443:443 -t l3iggs/owncloud /bin/bash
```

Then once you're in the image, run

```
cd '/usr'; sudo /usr/bin/mysqld_safe --datadir='/var/lib/mysql'& sudo apachectl -DFOREGROUND
```

and let me know how it responds for you.

I expect your prompt not to return. At that point the apache and mariadb servers should be running and the image should work like normal. If that command does return, we'll split their launching up and start to look into their error logs to figure out what's going on.

**Comment by sils** [comment]
Thanks, I'll try to get more info tomorrow.

**Comment by sils** [comment]
```
[docker@091e943eff5f conf]$ sudo /usr/bin/mysqld_safe --datadir='/var/lib/mysql'& sudo apachectl -DFOREGROUND
[1] 5
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.10. Set the 'ServerName' directive globally to suppress this message
150331 10:07:27 mysqld_safe Logging to '/var/lib/mysql/091e943eff5f.err'.
150331 10:07:27 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
[docker@091e943eff5f conf]$ 
```

returns immediately

**Comment by sils** [comment]
```
[docker@091e943eff5f conf]$ sudo cat /var/lib/mysql/091e943eff5f.err
150331 10:07:27 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
150331 10:07:27 [Note] InnoDB: Using mutexes to ref count buffer pool pages
150331 10:07:27 [Note] InnoDB: The InnoDB memory heap is disabled
150331 10:07:27 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
150331 10:07:27 [Note] InnoDB: Memory barrier is not used
150331 10:07:27 [Note] InnoDB: Compressed tables use zlib 1.2.8
150331 10:07:27 [Note] InnoDB: Using Linux native AIO
150331 10:07:27 [Note] InnoDB: Using CPU crc32 instructions
150331 10:07:27 [Note] InnoDB: Initializing buffer pool, size = 128.0M
150331 10:07:27 [Note] InnoDB: Completed initialization of buffer pool
150331 10:07:27 [Note] InnoDB: Highest supported file format is Barracuda.
150331 10:07:27 [Note] InnoDB: 128 rollback segment(s) are active.
150331 10:07:27 [Note] InnoDB: Waiting for purge to start
150331 10:07:27 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.22-72.0 started; log sequence number 1616707
150331 10:07:27 [Note] Plugin 'FEEDBACK' is disabled.
150331 10:07:28 [Note] Server socket created on IP: '::'.
150331 10:07:28 [Note] Event Scheduler: Loaded 0 events
150331 10:07:28 [Note] /usr/bin/mysqld: ready for connections.
Version: '10.0.17-MariaDB-log'  socket: '/run/mysqld/mysqld.sock'  port: 3306  MariaDB Server
[docker@091e943eff5f conf]$ 
```

**Comment by l3iggs** [comment]
I suspect the issue is with apache then. `sudo apachectl -DFOREGROUND` should not return immediately. Can you have a look in `/var/log/httpd/` please?

**Comment by sils** [comment]
logs are here: http://pastebin.com/xbLbYDGr

**Comment by sils** [comment]
```
[docker@a1c091b5e901 usr]$ sudo apachectl -DFOREGROUND
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.1. Set the 'ServerName' directive globally to suppress this message
[docker@a1c091b5e901 usr]$ 
```

**Comment by l3iggs** [comment]
Apache is not able to start because it can't create its pid file. From your pastebin'd log:

```
[Tue Mar 31 12:18:16.346478 2015] [core:error] [pid 10] (2)No such file or directory: AH00099: could not create /run/httpd/httpd.pid
[Tue Mar 31 12:18:16.346546 2015] [core:error] [pid 10] AH00100: httpd: could not log pid to file /run/httpd/httpd.pid
```

What does `ls -al /run/httpd` show in your container?
Try 

```
sudo mkdir -p /run/httpd
sudo chmod 777 /run/httpd
```

and then see if apache will run for you.

Does your kernel log on your host machine show anything interesting when you try to start apache in the container?

**Comment by sils** [comment]
seems to work

```
[docker@a1c091b5e901 usr]$  ls -al /run/httpd
ls: cannot access /run/httpd: No such file or directory
[docker@a1c091b5e901 usr]$ sudo mkdir -p /run/httpd
[docker@a1c091b5e901 usr]$ sudo chmod 777 /run/httpd
[docker@a1c091b5e901 usr]$ sudo apachectl -DFOREGROUND
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.1. Set the 'ServerName' directive globally to suppress this message
```

**Comment by l3iggs** [comment]
I find it difficult to imagine how the `/run/httpd` directory is disappearing from your images. Do you have any ideas how that could be? My owncloud containers in the docker registry have that folder.

I suspect either Fedora alpha or whatever non-release version of docker that might come with it are somehow to blame here.

**Comment by sils** [comment]
The suspicion sounds reasonable. Its indeed very weird that the file system differs within the image. How about creating that directory in the dockerfile if needed as a workaround?

**Comment by sils** [comment]
On Fedora 22 alpha 3:

```
[lasse@schuirlsrv ~]$ docker -v
Docker version 1.5.0-dev, build 5ebfacd/1.5.0
[lasse@schuirlsrv ~]$ docker run -i -t l3iggs/owncloud /bin/bash
[docker@841a4ca84813 conf]$ ls -al /run/httpd  
ls: cannot access /run/httpd: No such file or directory
```

On archlinux:

```
lasse@lssteadarch ~/prog % docker -v
Docker version 1.5.0, build a8a31ef
lasse@lssteadarch ~/prog % sudo docker run -i -t l3iggs/owncloud /bin/bash
[docker@6306d90d0b72 conf]$ ls -al /run/httpd
total 8
drwxr-xr-x 2 root root 4096 Mar 26 10:24 .
drwxr-xr-x 5 root root 4096 Mar 26 10:38 ..
[docker@6306d90d0b72 conf]$ 
```

I'll try to do more experiments.

**Comment by l3iggs** [comment]
This issue belongs on a Fedora bugtracker

**Comment by l3iggs** [comment]
I take it back.
I just experienced this issue with an Arch host. I've added a workaround for now (create /var/httpd folder before starting apache).

I'd like to understand why this is needed...

**Comment by l3iggs** [comment]
It looks like systemd typically creates the `/var/httpd` directory (which holds apache's pid file) when it starts the apache server service. Since I'm starting the apache server manually in the owncloud container, systemd is never invoked and so the `/var/httpd` is never created which means I have to create it manually in order for apache to be happy starting up. Don't ask me why I never had to do this before. I blame systemd :-|
