### ISSUE TITLE
flooding errorlog

### ISSUE THREAD

**Issue by cguentherTUChemnitz** [l3iggs/docker-owncloud#80]
the /var/log/httpd is flooded with 

`net: error while loading shared libraries: libfam.so.0: cannot open shared object file: No such file or directory`

statements. This file reached 262MB after 2 weeks of usage.
My used owncloud plugins:
external storage support
ldap plugin

**Comment by greyltc** [comment]
Hm. Trying to recreate this now...

**Comment by cguentherTUChemnitz** [comment]
I missed an important note:
I am running your 8.2.2-2  tagged image from dockerhub.

Thanks for looking into this.

**Comment by greyltc** [comment]
`/var/log/httpd` is a directory. Which log file do you see filling?
`error_log` I guess?

**Comment by cguentherTUChemnitz** [comment]
It floods the /var/log/httpd/error_log

**Comment by greyltc** [comment]
A lot has changed since the `8.2.2-2` tag. Can you try `latest` to see if your logs are filling then? (that's going to be ownCloud v9.0)

**Comment by cguentherTUChemnitz** [comment]
I will upgrade as soon i have enough time.  I will report back after upgrade. Thanks so far.

**Comment by greyltc** [comment]
I can't recreate the issue. `libfam.so.0` is part of the `gamin` package. I don't know what in your setup is needing that.

You might try this to install gamin in your (running) container (let's assume you started your container with `--name oc`):

```
docker exec -it oc sh -c 'pacman -Syy --noconfirm --needed gamin'
```

**Comment by cguentherTUChemnitz** [comment]
Thanks. It seem to quiet now. I don't what exactly uses this package.

**Comment by greyltc** [comment]
Well, from now on it'll be in the container: 81d6e35099d8737b5b33a87afc7c7e99811256b3
