### ISSUE TITLE
MYSQL / OWNCLOUD Not working together Please HELP!

### ISSUE THREAD

**Issue by ghost** [l3iggs/docker-owncloud#88]
I have installed Owncloud and MySQL through  Docker and i keep getting this response from OWNCLOUD while trying to set it up using mysql Database.  

Error while trying to create admin user: Failed to connect to the Database; An execption occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'172.17.42.1' (using password; YES)

I would appreciate anyhelp i can get. I have been working on this for a few days no with no luck searching the web and finding somethings but nothing seems to be exactly  the issue i am having.

**Comment by ghost** [comment]
HELP PLEASE

**Comment by Undeadhunter** [comment]
Are you sure your SQL Database has been setup correctly? Can you reach it through the CLI on the IP 172.17.42.1 ?

**Comment by ghost** [comment]
Undeadhunter as far as i can tell its been setup correctly, the details  'root'@'172.17.42.1' (using password; YES)  seem to be a "default" as my sql server ip is 192.168.0.123:3306 which i can reach fine. 

I have tried to link both containers but own cloud is still pointed at the 172.17.42.1 address.

**Comment by Undeadhunter** [comment]
External sql or the build in one? If the build in one you made a mistake while doing the setup 

https://github.com/l3iggs/docker-owncloud/wiki/Setup-ownCloud-to-use-MySQL-instead-of-the-default-sqlite-database

**Comment by ghost** [comment]
I have tried both an external sql and the internal. 
Would you be able to tell me step by step install and i will see if that fixes it?

**Comment by greyltc** [comment]
I just tested it, and the internal SQL server seems to be working fine.
Step by step:
1. Follow steps 1-3 in the [README.md](https://github.com/l3iggs/docker-owncloud/blob/master/README.md)
2. Follow the steps on the above linked [wiki page](https://github.com/l3iggs/docker-owncloud/wiki/Setup-ownCloud-to-use-MySQL-instead-of-the-default-sqlite-database) to configure your server to use the built-in mariaDB SQL server.

**Comment by ghost** [comment]
Cheers still having issues but i will try another docker build i think. Supports not here. 
Ta

**Comment by HaVonTe1** [comment]
I have th exact same issue. No matter what I type in the host field for the mysql it says "Access denied for user root@172.17.2. Using Password: YES"
Where the IP 172.17.0.2 is the IP of the owncloud container. What am I missing here?
