### ISSUE TITLE
Any possibility to skip the /owncloud and get it to run in the "root folder" of the URL?

### ISSUE THREAD

**Issue by marcus-no** [l3iggs/docker-owncloud#89]
I would like to access the container from my.domain.tld instead of my.domain.tld/owncloud.

Is this possible in any way?

**Comment by elangelo** [comment]
https://github.com/l3iggs/docker-owncloud/wiki/Environment-Variables

there is quite some documentation on this image/container... it might be nice if you bothered reading it...

**Comment by marcus-no** [comment]
Sorry about that. The containers I've used up till now usually have "all" their doc on the docker hub page, so I didn't remotely think of looking at the wiki page. I'll keep that it in mind for later.

That being said...no reason to be a dick about it.
