### ISSUE TITLE
Dependencies 404

### ISSUE THREAD

**Issue by raqbit** [l3iggs/docker-owncloud#90]
When using "docker build ." to build this image, I get 404's for stuff like Iptables and other packages. Can you please update this to have up to date packages? Thanks.

Also: Because of this error my owncloud install is offline, and I can't get it back with the custom IRL I made it have.

**Comment by greyltc** [comment]
Hi @JustRamon, I've added a new feature to the container to address this. I don't think the right thing is to rebuild the whole image stack whenever a package is out of date.
Have a look at [line number 8 of the Dockerfile](https://github.com/l3iggs/docker-owncloud/blob/master/Dockerfile#L8).

When you uncomment that line, the mirrorlist in your image will be updated and then any subsequent package installs you do should go fine.

Please let me know if that solves things for you.

**Comment by raqbit** [comment]
zsh:1: command not found: get-new-mirrors
The command '/bin/sh -c get-new-mirrors' returned a non-zero code: 127

**Comment by greyltc** [comment]
I assume that's because you haven't updated. `docker pull l3iggs/owncloud`

**Comment by raqbit** [comment]
No, that's what I'm getting when I build from the github repo.

**Comment by greyltc** [comment]
Run the pull command. Your parent image is out of date.

**Comment by raqbit** [comment]
I'm pulling the source already. I even removed the dir & cloned it back. Still not working :/

**Comment by raqbit** [comment]
git clone https://github.com/l3iggs/docker-owncloud.git && cd docker-owncloud && nano Dockerfile (to make changes) && docker build .

**Comment by greyltc** [comment]
You need to run the docker pull command as I suggested [5 comments ago](https://github.com/l3iggs/docker-owncloud/issues/90#issuecomment-216001624).

**Comment by raqbit** [comment]
It is already up to date

**Comment by greyltc** [comment]
I'm having a very hard time understanding how your images could possibly be up to date while you're getting `command not found: get-new-mirrors`.

What does `docker inspect l3iggs/owncloud | grep Created` return on your system?

**Comment by raqbit** [comment]
2016-04-30T18:38:58.316812665Z

**Comment by raqbit** [comment]
But what has pulling the image to do with building it from the git repo?

**Comment by greyltc** [comment]
Running the `docker pull` command as I suggested above updates the entire chain of docker containers that comprises `l3iggs/owncloud`. You can see at the top of the Dockerfile in this repo that it doesn't start from scratch, it starts from `greyltc/lamp-aur`.

When you do a `docker build .` in the git repo here, you're just re-building the last few layers of the full container, not the whole thing. docker doesn't bother to check if any of its parent containers are out of date or not on a `docker build`, so you have to be sure your local copies of those are up to date.

The `get-new-mirrors` feature I added was in one of the parent containers, so if you don't update those (via `docker pull`, you'll obviously get a `command not found` error when you try to use the new command I've added for you.

**Comment by raqbit** [comment]
I deleted all relating images & pulled it fresh. Now it's building correctly! Thanks for helping, and sorry for being a little stupid lol

**Comment by raqbit** [comment]
On a side note, why is it installing gtk & libre office fresh? Lol

**Comment by greyltc** [comment]
No prob.
Yeah, I know; tons of stupid (pointless) deps are pulled in by some of those packages. libre office fresh is used for rendering & editing of .doc .odt and .docx files right in the browser.

**Comment by raqbit** [comment]
Ah, that explains :P
Also I got Owncloud back up and running.
