### ISSUE TITLE
My Owncloud image went from 2.5GB to 7.5GB in 5 weeks... Reason?

### ISSUE THREAD

**Issue by robclay** [l3iggs/docker-owncloud#96]
I was just doing some maintenance... stopped my container / committed it.

I saw that my image file is now 5 GB larger than it was 5 weeks ago.  I store my files external to the docker container, so I am assuming that is not the issue.  Is it a log file that is growing, and is there some maintenance I should be doing?  Or what else would you suggest?

Thanks,
Robert

**Comment by robclay** [comment]
On further review, I don't _think_ that it is the owncloud log, as I just downloaded it, and it is only 2.5MB.

**Comment by greyltc** [comment]
Assuming you've named your ownCloud container `oc` when you created it, what does `docker exec -t oc du -hd1 /usr/share/webapps/owncloud/` give?

For a fresh container it's something like:

```
$ docker exec -t oc du -hd1 /usr/share/webapps/owncloud/
28M /usr/share/webapps/owncloud/3rdparty
37M /usr/share/webapps/owncloud/apps
0   /usr/share/webapps/owncloud/assets
48K /usr/share/webapps/owncloud/config
29M /usr/share/webapps/owncloud/core
3.0M    /usr/share/webapps/owncloud/data
20K /usr/share/webapps/owncloud/l10n
6.2M    /usr/share/webapps/owncloud/lib
16K /usr/share/webapps/owncloud/ocs
8.0K    /usr/share/webapps/owncloud/ocs-provider
880K    /usr/share/webapps/owncloud/resources
3.1M    /usr/share/webapps/owncloud/settings
60K /usr/share/webapps/owncloud/themes
2.8M    /usr/share/webapps/owncloud/updater
110M    /usr/share/webapps/owncloud/
```

**Comment by robclay** [comment]
Grey,
30M     /usr/share/webapps/owncloud/3rdparty
237G    /usr/share/webapps/owncloud/data
12K     /usr/share/webapps/owncloud/ocs-provider
52K     /usr/share/webapps/owncloud/config
3.1M    /usr/share/webapps/owncloud/updater
28K     /usr/share/webapps/owncloud/l10n
6.7M    /usr/share/webapps/owncloud/lib
940K    /usr/share/webapps/owncloud/resources
80K     /usr/share/webapps/owncloud/themes
3.1M    /usr/share/webapps/owncloud/settings
30M     /usr/share/webapps/owncloud/core
47M     /usr/share/webapps/owncloud/apps
20K     /usr/share/webapps/owncloud/ocs
4.0K    /usr/share/webapps/owncloud/assets
238G    /usr/share/webapps/owncloud/

Is it the overhead to keep the large amount of data?

Thanks for any help.  And it still works fine... I am just trying to educate myself on how it all fits together!
- Robert

**Comment by greyltc** [comment]
@robclay you mentioned you're storing your storing your data outside the container. You might want to double check that assumption somehow in case your data is going into the container and not being stored externally.

Maybe you could run `docker exec -t oc du -hd1 /usr/share/webapps/owncloud/`
After you've started your container without the volume mount for your data folder?

**Comment by robclay** [comment]
greyltc,, Sorry for a much later response... I just 'committed' my container, and it is taking up 12.41GB.  My storage space of files is about 600Gig.  It is definitely separate.  Anything else you can think of?
