### ISSUE TITLE
letsencrypt script missing

### ISSUE THREAD

**Issue by torwag** [l3iggs/docker-owncloud#98]
Hi, I have a very strange problem,
My certificates were not renewed and looking into it, I notice that follwoing error message 

`/usr/bin/setup-apache-ssl-key: line 38: letsencrypt: command not found`

Also a search does not find anything related to letsencrypt, like it is not installed at all. I set-up the owncloud container again, but also this one seems to contain now letsencrypt folder.

**Comment by greyltc** [comment]
:-/
Looks like letsencrypt has undergone a bunch of refactoring upstream. 
Apparently it's now called `certbot`. 
It's going to be a bit of work for me to get this working again.

**Comment by greyltc** [comment]
@torwag I think I've fixed this now. I've also updated made some improvements so that hopefully your certificates will be auto-renewed now.
The trick there was to create a cron job that runs `certbot renew` twice daily.
Please let me know if things are working for you now.

**Comment by filcuc** [comment]
in which branch it should be fixed?

**Comment by filcuc** [comment]
@greyltc

**Comment by greyltc** [comment]
Hi @filcuc, I made this fix [in an upstream docker image on which this project depends](https://github.com/greyltc/docker-LAMP/commit/d2ec9030a61185ed853d1d656dce6db9fdc2f5e3). Any image associated with this repo that was built after July 3 will incorporate the fix. That means containers built from the following branches here (and any newer ones I create) contain the fix:
daily
master
9.1.0-1

On your end, `docker pull l3iggs/owncloud` is equivalent to `docker pull l3iggs/owncloud:latest` which uses the master branch. To pull any other branch, put its name after a colon after the container's name like this:  `docker pull l3iggs/owncloud:9.1.0-1`

**Comment by greyltc** [comment]
By the way, I'm marking this fixed because it's been over a month and @torwag doesn't seem to want to verify for me that my work here has fixed his/her problem :-/

**Comment by filcuc** [comment]
@greyltc i came here because i've experienced this issue with the next-cloud image but i'll try again and maybe open the ticket in the next-cloud repo

**Comment by greyltc** [comment]
Sounds good.
