### ISSUE TITLE
Refused to connect.

### ISSUE THREAD

**Issue by ghost** [l3iggs/docker-owncloud#99]
I've run the container using 
 docker run --name oc -p 800:80 -p 4430:443 -d l3iggs/owncloud

I have Nginx running reverse proxy on 80 and 443 already so I just added a zero onto the provided ports. When trying to connect to the container it gives a Refused to connect error. When I bound a port via ssh -D and tried connecting to it locally it still gave this error. This is on a fresh install of Arch Linux. The only major changes I've made to the system is yanking out the old 3.14 kernel provided by OVH and replaced it with the current Linux Kernel. I've used this exact setup before so I'm surprised it's giving me so much trouble.

Any ideas as to what could be causing this? There is no iptable rules or firewall active.

**Comment by greyltc** [comment]
I'll have a look at it now.

**Comment by greyltc** [comment]
Yep. I broke it yesterday by accident. Fixing now...

**Comment by greyltc** [comment]
Should be fixed now. Sorry about the breakage.
Please `pull l3iggs/owncloud` and confirm here that things are working for you.

**Comment by ghost** [comment]
Confirm things are working. Thanks !
